### ISSUE TITLE
Fixing the Footer

### ISSUE THREAD

**Issue by MarcoMorawec** [JonnShaft/splurty#2]
The footer looks like it's not properly being pulled to the right hand side of the screen.

I think this is a pretty quick fix, but will make your app look more polished. I'd say, give it a go.

Here's what I see:

![screen shot 2015-06-10 at 12 03 25 pm](https://cloud.githubusercontent.com/assets/1474717/8087447/ed7597a6-0f68-11e5-9394-065540a81b6f.png)

**Comment by JonnShaft** [comment]
Got it. Thanks Marco. The footer is now right-justified.

**Comment by MarcoMorawec** [comment]
@JonnShaft :+1:
